# In zenithdb-server/Cargo.toml
[package]
name = "zenithdb-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
# No more external bloom filter crates
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"